name: Maven package & start release
  
on:
  push:
    tags: 
      - '*.*.*'

jobs:
  call-release:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set env
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> "$GITHUB_ENV"

    - name: Get Commit Message
      id: get_commit_message
      run: |
        MSG=$(git log --format=%B -n 1 ${{github.event.after}})
        echo "COMMIT_MESSAGE=${MSG}" >> "$GITHUB_ENV"

    - name: Get Tag
      id: get_tag
      run: |
        echo "TAG=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

    - name: Set Payload
      id: set_payload
      run: |
        echo "PAYLOAD={\"tag\":\"${{ env.TAG }}\", \"commit_message\":\"${{ env.COMMIT_MESSAGE }}\"}" >> $GITHUB_ENV

    - name: Test
      run: |
        echo ${{ env.PAYLOAD }}
        
    - name: Trigger Release Template 
      env:
        XLR_URL: ${{ secrets.XLR_URL }}   
      run: echo "'${{ secrets.XLR_URL }}/webhooks/githubendpoint' --header 'Content-Type:application/json' --data \"${{env.PAYLOAD}}\""
   